# Generated by Django 6.0.4 on 2026-04-27 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('New', 'New'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved')], default='New', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Enquiries',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Cardio', 'Cardio'), ('Strength', 'Strength'), ('Free Weights', 'Free Weights'), ('Functional', 'Functional'), ('Other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('quantity', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('Working', 'Working'), ('Under Maintenance', 'Under Maintenance'), ('Out of Order', 'Out of Order')], default='Working', max_length=20)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('last_maintenance', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
