# Generated by Django 5.2.1 on 2026-05-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_enquiry_equipment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="package",
            name="duration",
            field=models.IntegerField(
                choices=[
                    (1, "1 month"),
                    (3, "3 months"),
                    (6, "6 months"),
                    (12, "12 months"),
                ]
            ),
        ),
    ]
